# Browse the complete list of string methods at:
# https://docs.python.org/3/library/stdtypes.html#string-methods
# and try them out here. Endeavor to copy the link without the first # comment sign beginning it.

myString = "josteve"
myTabbedString = "name\tage\tsex"
myExpressionString = "The sum of 1 + 2 is {0}"

print(myString.capitalize())
print(myString.center(2))
print(myString.casefold())
print(myString.count("e"))
print(myString.encode())
print(myString.endswith("evv"))
print(myTabbedString.expandtabs(10))
print(myString.find("s"))
print(myExpressionString.format(1 + 2))
print("my name is {name}, I am {age}".format_map({"name": myString, "age": 10}))
print(myString.index("e"))
print(myString.isalnum())
print(myString.isalpha())
print(myString.isascii())
print(myString.isdecimal())
print(myString.isdigit())
print(myString.isidentifier())
print(myString.islower())
print(myString.isnumeric())
print(myString.isprintable())
print(myString.isspace())
print(myString.istitle())
print(myString.isupper())
print(myString.join("hi"))
print(myString.ljust(2))
print(myString.lstrip())
print(myString.maketrans("r", "o", "p"))
print((myString * 3).partition("jo"))
print(myString.replace("jo", "ma"))
print(myString.rfind("e"))
print(myString.rindex("v"))
print(myString.rpartition("e"))
print(myString.rsplit(maxsplit=3, sep="e"))
print(myString.rstrip())
print(myString.splitlines())
print(myString.startswith("me"))
print(myString.swapcase())
print(myString.title())
print(myString.translate("e"))
print(myString.isupper())
print(myString.zfill(2))
